export const USERNAME_LOCALSTORAGE = 'USERNAME_LOCALSTORAGE'

export const ROUTER_PATHS = {
  welcome: '/',
  activeUsers: '/active-users',
  game: '/game',
}

export const SOCKET_SERVER_URL = 'http://127.0.0.1:3000'

export const SOCKET_CHANNELS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  DISCONNECT: 'disconnect',
  ALREADY_EXIST_USERNAME: 'ALREADY_EXIST_USERNAME',
  CORRECT_USERNAME_TO_LOGIN: 'CORRECT_USERNAME_TO_LOGIN',
  ACTIVE_USERS: 'ACTIVE_USERS',
  SEND_GAME_REQUEST: 'SEND_GAME_REQUEST',
  INCOMING_GAME_REQUEST: 'INCOMING_GAME_REQUEST',
  CANCEL_GAME_REQUEST: 'CANCEL_GAME_REQUEST',
  ACCEPT_GAME_REQUEST: 'ACCEPT_GAME_REQUEST',
  GAME_CANCELED: 'GAME_CANCELED',
}
